
*Midline Water
list dataid UniqueIDW if dataid=="35601" & UniqueIDW==""
list dataid UniqueIDW if dataid=="35602" & UniqueIDW==""
list dataid UniqueIDW if dataid=="35604" & UniqueIDW==""
list dataid UniqueIDW if dataid=="35605" & UniqueIDW==""
list dataid UniqueIDW if dataid=="35606" & UniqueIDW==""
list dataid UniqueIDW if dataid=="35607" & UniqueIDW==""
list dataid UniqueIDW if dataid=="37906" & UniqueIDW==""
list dataid UniqueIDW if dataid=="37907" & UniqueIDW==""
list dataid UniqueIDW if dataid=="37908" & UniqueIDW==""
list dataid UniqueIDW if dataid=="38401" & UniqueIDW==""
list dataid UniqueIDW if dataid=="38402" & UniqueIDW==""
list dataid UniqueIDW if dataid=="38403" & UniqueIDW==""
list dataid UniqueIDW if dataid=="38404" & UniqueIDW==""
list dataid UniqueIDW if dataid=="38405" & UniqueIDW==""
list dataid UniqueIDW if dataid=="38406" & UniqueIDW==""
list dataid UniqueIDW if dataid=="38901" & UniqueIDW==""
list dataid UniqueIDW if dataid=="38904" & UniqueIDW==""
list dataid UniqueIDW if dataid=="38906" & UniqueIDW==""
list dataid UniqueIDW if dataid=="38907" & UniqueIDW==""
list dataid UniqueIDW if dataid=="45701" & UniqueIDW==""
list dataid UniqueIDW if dataid=="45703" & UniqueIDW==""
list dataid UniqueIDW if dataid=="45704" & UniqueIDW==""
list dataid UniqueIDW if dataid=="48204" & UniqueIDW==""
list dataid UniqueIDW if dataid=="52401" & UniqueIDW==""
list dataid UniqueIDW if dataid=="52402" & UniqueIDW==""
list dataid UniqueIDW if dataid=="52403" & UniqueIDW==""
list dataid UniqueIDW if dataid=="52405" & UniqueIDW==""
list dataid UniqueIDW if dataid=="52406" & UniqueIDW==""
list dataid UniqueIDW if dataid=="52407" & UniqueIDW==""
list dataid UniqueIDW if dataid=="52408" & UniqueIDW==""
list dataid UniqueIDW if dataid=="53703" & UniqueIDW==""
list dataid UniqueIDW if dataid=="53901" & UniqueIDW==""
list dataid UniqueIDW if dataid=="64103" & UniqueIDW==""
list dataid UniqueIDW if dataid=="64106" & UniqueIDW==""
list dataid UniqueIDW if dataid=="64107" & UniqueIDW==""
list dataid UniqueIDW if dataid=="64108" & UniqueIDW==""
list dataid UniqueIDW if dataid=="67203" & UniqueIDW==""
list dataid UniqueIDW if dataid=="67204" & UniqueIDW==""
list dataid UniqueIDW if dataid=="67206" & UniqueIDW==""
list dataid UniqueIDW if dataid=="71304" & UniqueIDW==""
list dataid UniqueIDW if dataid=="71803" & UniqueIDW==""
list dataid UniqueIDW if dataid=="71805" & UniqueIDW==""
list dataid UniqueIDW if dataid=="71806" & UniqueIDW==""
list dataid UniqueIDW if dataid=="71807" & UniqueIDW==""
list dataid UniqueIDW if dataid=="71808" & UniqueIDW==""


*Midline hands
list dataid UniqueIDH if dataid=="37505" & UniqueIDH==""
list dataid UniqueIDH if dataid=="40805" & UniqueIDH==""
list dataid UniqueIDH if dataid=="49707" & UniqueIDH==""
list dataid UniqueIDH if dataid=="65206" & UniqueIDH==""
list dataid UniqueIDH if dataid=="66303" & UniqueIDH==""


*Midline toys
list dataid UniqueIDT if dataid=="64403" & UniqueIDT==""


